name: cloudpayments_upgraded
description: A Flutter plugin for integrating Cloudpaymanets in Android and iOS applications.
version: 0.4.3
repository: https://github.com/shoshideveloper/cloudpayments_upgraded
homepage: https://pub.dev/packages/cloudpayments_upgraded

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shushper.cloudpayments
        pluginClass: CloudpaymentsPlugin
      ios:
        pluginClass: CloudpaymentsPlugin

